spring.application.name=GoPoli
server.port=${PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/gopoli}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:gopoli}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:gopoli}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.properties.hibernate.format_sql=${SPRING_JPA_FORMAT_SQL:true}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

gopoli.jwt.secret=${GOPOLI_JWT_SECRET:GoPoliDevSecretKeyMinimo32Caracteres!!}
gopoli.jwt.expiration-hours=${GOPOLI_JWT_EXPIRATION_HOURS:168}
